"""Shared pytest fixtures for the PostLikeMe test suite.

Provides reusable sample data (tweets, profiles, configs) and temporary
directory helpers so that individual test modules can focus on assertions
rather than setup boilerplate.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pytest

from postlikeme.models.raw_tweet import CleanTweet, EmojiPosition, RawTweet, UserProfile
from postlikeme.models.voice_profile import (
    BigFiveScores,
    CapitalizationPatterns,
    EmojiProfile,
    ExampleTweets,
    HashtagProfile,
    OpinionEntry,
    PersonalityProfile,
    PunctuationPatterns,
    ReadabilityScores,
    ReplyStyle,
    SemanticCluster,
    StructuralStyle,
    TopicEntry,
    TopicProfile,
    TweetLengthDistribution,
    VoiceProfile,
)
from postlikeme.models.config import AppConfig


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Sample tweets
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_tweets() -> list[RawTweet]:
    """Return 25 diverse sample tweets covering many edge cases."""
    return [
        # 1. Regular original tweet with emoji and hashtag
        RawTweet(
            id="1",
            text="Just shipped a new feature! \U0001f680 Really proud of the team #buildinpublic",
            created_at=datetime(2024, 1, 15, 10, 30, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=["buildinpublic"],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=42,
            retweet_count=8,
            reply_count=3,
            language="en",
        ),
        # 2. Reply tweet
        RawTweet(
            id="2",
            text="@johndoe That's a great point! I totally agree with your take on this.",
            created_at=datetime(2024, 1, 15, 11, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="johndoe",
            reply_to_tweet_id="999",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["johndoe"],
            urls=[],
            media_types=[],
            like_count=5,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        # 3. Retweet
        RawTweet(
            id="3",
            text="RT @techguru: The future of AI is here and it is AMAZING",
            created_at=datetime(2024, 1, 14, 8, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=True,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["techguru"],
            urls=[],
            media_types=[],
            like_count=0,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        # 4. Quote tweet
        RawTweet(
            id="4",
            text="This is exactly why we need better tooling \U0001f4af",
            created_at=datetime(2024, 1, 13, 15, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=True,
            quoted_text="Our developer tools are outdated and slowing everyone down",
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=120,
            retweet_count=25,
            reply_count=10,
            language="en",
        ),
        # 5. Short tweet (< 50 chars)
        RawTweet(
            id="5",
            text="Good morning!",
            created_at=datetime(2024, 1, 12, 7, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=2,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        # 6. Long tweet (> 200 chars)
        RawTweet(
            id="6",
            text=(
                "I've been thinking a lot about the intersection of technology and "
                "creativity lately. It seems like every day there's a new tool that "
                "promises to revolutionize how we work, but the real magic happens "
                "when humans and machines collaborate rather than compete."
            ),
            created_at=datetime(2024, 1, 11, 20, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=89,
            retweet_count=15,
            reply_count=7,
            language="en",
        ),
        # 7. Question tweet
        RawTweet(
            id="7",
            text="What's the best programming language for beginners in 2024? Genuinely curious.",
            created_at=datetime(2024, 1, 10, 14, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=30,
            retweet_count=5,
            reply_count=45,
            language="en",
        ),
        # 8. Exclamation tweet with ALL CAPS
        RawTweet(
            id="8",
            text="WE DID IT! The app just hit 1 MILLION downloads! INCREDIBLE!!!",
            created_at=datetime(2024, 1, 9, 18, 30, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=500,
            retweet_count=120,
            reply_count=50,
            language="en",
        ),
        # 9. Tweet with URL
        RawTweet(
            id="9",
            text="Check out my latest blog post on microservices https://t.co/abc123",
            created_at=datetime(2024, 1, 8, 12, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=["https://example.com/blog/microservices"],
            media_types=[],
            like_count=15,
            retweet_count=3,
            reply_count=2,
            language="en",
        ),
        # 10. URL-only tweet
        RawTweet(
            id="10",
            text="https://t.co/xyz789",
            created_at=datetime(2024, 1, 7, 9, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=["https://example.com/something"],
            media_types=[],
            like_count=1,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        # 11. Mention-only tweet
        RawTweet(
            id="11",
            text="@alice @bob @charlie",
            created_at=datetime(2024, 1, 6, 16, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["alice", "bob", "charlie"],
            urls=[],
            media_types=[],
            like_count=0,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        # 12. Tweet with multiple emojis
        RawTweet(
            id="12",
            text="\U0001f525\U0001f525\U0001f525 This is absolutely fire! \U0001f4aa\U0001f3fb Best day ever \u2764\ufe0f",
            created_at=datetime(2024, 1, 5, 21, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=75,
            retweet_count=10,
            reply_count=5,
            language="en",
        ),
        # 13. Tweet with multiple hashtags
        RawTweet(
            id="13",
            text="Excited for the conference! #tech #AI #MachineLearning #future #innovation",
            created_at=datetime(2024, 1, 4, 10, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=["tech", "AI", "MachineLearning", "future", "innovation"],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=20,
            retweet_count=5,
            reply_count=2,
            language="en",
        ),
        # 14. Sarcastic tweet
        RawTweet(
            id="14",
            text="Oh great, another meeting that could have been an email. Love it.",
            created_at=datetime(2024, 1, 3, 14, 30, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=200,
            retweet_count=50,
            reply_count=20,
            language="en",
        ),
        # 15. Tweet with media
        RawTweet(
            id="15",
            text="The sunset from my office window today \U0001f305",
            created_at=datetime(2024, 1, 2, 17, 30, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=["image"],
            like_count=35,
            retweet_count=2,
            reply_count=4,
            language="en",
        ),
        # 16. Reply with disagreement
        RawTweet(
            id="16",
            text="@skeptic I have to disagree here. The data clearly shows the opposite trend.",
            created_at=datetime(2024, 1, 1, 11, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="skeptic",
            reply_to_tweet_id="888",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["skeptic"],
            urls=[],
            media_types=[],
            like_count=8,
            retweet_count=1,
            reply_count=3,
            language="en",
        ),
        # 17. Thread-like tweet
        RawTweet(
            id="17",
            text="Thread on why I think remote work is here to stay (1/5):",
            created_at=datetime(2023, 12, 30, 9, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=60,
            retweet_count=20,
            reply_count=15,
            language="en",
        ),
        # 18. Food tweet
        RawTweet(
            id="18",
            text="Made homemade ramen tonight and it was bussin fr \U0001f35c\U0001f60b",
            created_at=datetime(2023, 12, 28, 20, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=["image"],
            like_count=25,
            retweet_count=3,
            reply_count=8,
            language="en",
        ),
        # 19. Sports tweet
        RawTweet(
            id="19",
            text="WHAT A GAME! Down by 20 and came back to win in OT!! #NBA #Lakers",
            created_at=datetime(2023, 12, 25, 22, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=["NBA", "Lakers"],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=150,
            retweet_count=40,
            reply_count=25,
            language="en",
        ),
        # 20. Opinion tweet
        RawTweet(
            id="20",
            text="Hot take: tabs are objectively better than spaces and I will die on this hill.",
            created_at=datetime(2023, 12, 20, 13, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=300,
            retweet_count=80,
            reply_count=150,
            language="en",
        ),
        # 21. Tweet with ellipsis and em-dash
        RawTweet(
            id="21",
            text="Sometimes I wonder... is all this hustle culture worth it\u2014or are we just burning out?",
            created_at=datetime(2023, 12, 18, 23, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=95,
            retweet_count=22,
            reply_count=18,
            language="en",
        ),
        # 22. Tweet with parenthetical
        RawTweet(
            id="22",
            text="Finally finished the refactor (only took 3 weeks lol) and the codebase is SO much cleaner now",
            created_at=datetime(2023, 12, 15, 16, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=45,
            retweet_count=6,
            reply_count=12,
            language="en",
        ),
        # 23. Reply with emoji lead
        RawTweet(
            id="23",
            text="\U0001f64f @helper Thanks so much for the code review! Really helpful feedback.",
            created_at=datetime(2023, 12, 12, 10, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="helper",
            reply_to_tweet_id="777",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["helper"],
            urls=[],
            media_types=[],
            like_count=3,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        # 24. Minimal tweet
        RawTweet(
            id="24",
            text="mood",
            created_at=datetime(2023, 12, 10, 2, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=10,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        # 25. Tweet with Unicode / accented characters
        RawTweet(
            id="25",
            text="Caf\u00e9 culture in Paris is something else. Cr\u00e8me br\u00fbl\u00e9e and a caf\u00e9 au lait \U0001f1eb\U0001f1f7",
            created_at=datetime(2023, 12, 8, 15, 0, tzinfo=timezone.utc),
            is_reply=False,
            reply_to_user=None,
            reply_to_tweet_id=None,
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=[],
            urls=[],
            media_types=[],
            like_count=55,
            retweet_count=8,
            reply_count=6,
            language="en",
        ),
    ]


@pytest.fixture
def sample_reply_tweets() -> list[RawTweet]:
    """Return 10 sample reply tweets with diverse patterns."""
    return [
        RawTweet(
            id="r1",
            text="@alice Totally agree! This is spot on.",
            created_at=datetime(2024, 1, 15, 10, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="alice",
            reply_to_tweet_id="100",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["alice"],
            urls=[],
            media_types=[],
            like_count=5,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        RawTweet(
            id="r2",
            text="@bob Hmm, I'm not sure about that. The numbers don't add up.",
            created_at=datetime(2024, 1, 14, 9, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="bob",
            reply_to_tweet_id="101",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["bob"],
            urls=[],
            media_types=[],
            like_count=3,
            retweet_count=0,
            reply_count=2,
            language="en",
        ),
        RawTweet(
            id="r3",
            text="@carol lol that's hilarious \U0001f602\U0001f602",
            created_at=datetime(2024, 1, 13, 18, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="carol",
            reply_to_tweet_id="102",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["carol"],
            urls=[],
            media_types=[],
            like_count=8,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        RawTweet(
            id="r4",
            text="@dave Great question! So the way it works is: first you initialize the config, then you run the pipeline.",
            created_at=datetime(2024, 1, 12, 14, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="dave",
            reply_to_tweet_id="103",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["dave"],
            urls=[],
            media_types=[],
            like_count=12,
            retweet_count=2,
            reply_count=3,
            language="en",
        ),
        RawTweet(
            id="r5",
            text="@eve Congrats on the launch!!! \U0001f389\U0001f389\U0001f389",
            created_at=datetime(2024, 1, 11, 11, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="eve",
            reply_to_tweet_id="104",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["eve"],
            urls=[],
            media_types=[],
            like_count=6,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        RawTweet(
            id="r6",
            text="@frank No, that's not right. The documentation specifically states otherwise.",
            created_at=datetime(2024, 1, 10, 16, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="frank",
            reply_to_tweet_id="105",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["frank"],
            urls=[],
            media_types=[],
            like_count=2,
            retweet_count=0,
            reply_count=4,
            language="en",
        ),
        RawTweet(
            id="r7",
            text="@grace \U0001f64f Thanks for sharing this!",
            created_at=datetime(2024, 1, 9, 8, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="grace",
            reply_to_tweet_id="106",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["grace"],
            urls=[],
            media_types=[],
            like_count=4,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        RawTweet(
            id="r8",
            text="@heidi Have you tried turning it off and on again? Works every time \U0001f602",
            created_at=datetime(2024, 1, 8, 20, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="heidi",
            reply_to_tweet_id="107",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["heidi"],
            urls=[],
            media_types=[],
            like_count=15,
            retweet_count=1,
            reply_count=2,
            language="en",
        ),
        RawTweet(
            id="r9",
            text="@ivan I wrote a thread about this last week, let me find the link",
            created_at=datetime(2024, 1, 7, 13, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="ivan",
            reply_to_tweet_id="108",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["ivan"],
            urls=[],
            media_types=[],
            like_count=7,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        RawTweet(
            id="r10",
            text="@judy THIS. So much this. Couldn't have said it better myself.",
            created_at=datetime(2024, 1, 6, 22, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="judy",
            reply_to_tweet_id="109",
            is_retweet=False,
            is_quote_tweet=False,
            quoted_text=None,
            hashtags=[],
            mentions=["judy"],
            urls=[],
            media_types=[],
            like_count=20,
            retweet_count=3,
            reply_count=0,
            language="en",
        ),
    ]


@pytest.fixture
def sample_clean_tweets() -> list[CleanTweet]:
    """Return pre-cleaned tweets for downstream analysis testing."""
    return [
        CleanTweet(
            id="c1",
            text="Just shipped a new feature! Really proud of the team",
            original_text="Just shipped a new feature! \U0001f680 Really proud of the team #buildinpublic",
            created_at=datetime(2024, 1, 15, 10, 30, tzinfo=timezone.utc),
            is_reply=False,
            emoji_positions=[
                EmojiPosition(emoji="\U0001f680", match_start=28, match_end=29, position_ratio=0.38),
            ],
            hashtags=["buildinpublic"],
            like_count=42,
            retweet_count=8,
            reply_count=3,
            language="en",
        ),
        CleanTweet(
            id="c2",
            text="@USER That's a great point! I totally agree with your take on this.",
            original_text="@johndoe That's a great point! I totally agree with your take on this.",
            created_at=datetime(2024, 1, 15, 11, 0, tzinfo=timezone.utc),
            is_reply=True,
            reply_to_user="johndoe",
            reply_to_tweet_id="999",
            original_mentions=["johndoe"],
            like_count=5,
            retweet_count=0,
            reply_count=1,
            language="en",
        ),
        CleanTweet(
            id="c3",
            text="What's the best programming language for beginners in 2024? Genuinely curious.",
            original_text="What's the best programming language for beginners in 2024? Genuinely curious.",
            created_at=datetime(2024, 1, 10, 14, 0, tzinfo=timezone.utc),
            is_reply=False,
            like_count=30,
            retweet_count=5,
            reply_count=45,
            language="en",
        ),
        CleanTweet(
            id="c4",
            text="WE DID IT! The app just hit 1 MILLION downloads! INCREDIBLE!!!",
            original_text="WE DID IT! The app just hit 1 MILLION downloads! INCREDIBLE!!!",
            created_at=datetime(2024, 1, 9, 18, 30, tzinfo=timezone.utc),
            is_reply=False,
            like_count=500,
            retweet_count=120,
            reply_count=50,
            language="en",
        ),
        CleanTweet(
            id="c5",
            text="Hot take: tabs are objectively better than spaces and I will die on this hill.",
            original_text="Hot take: tabs are objectively better than spaces and I will die on this hill.",
            created_at=datetime(2023, 12, 20, 13, 0, tzinfo=timezone.utc),
            is_reply=False,
            like_count=300,
            retweet_count=80,
            reply_count=150,
            language="en",
        ),
        CleanTweet(
            id="c6",
            text="Sometimes I wonder... is all this hustle culture worth it -- or are we just burning out?",
            original_text="Sometimes I wonder... is all this hustle culture worth it\u2014or are we just burning out?",
            created_at=datetime(2023, 12, 18, 23, 0, tzinfo=timezone.utc),
            is_reply=False,
            like_count=95,
            retweet_count=22,
            reply_count=18,
            language="en",
        ),
        CleanTweet(
            id="c7",
            text="Good morning!",
            original_text="Good morning!",
            created_at=datetime(2024, 1, 12, 7, 0, tzinfo=timezone.utc),
            is_reply=False,
            like_count=2,
            retweet_count=0,
            reply_count=0,
            language="en",
        ),
        CleanTweet(
            id="c8",
            text="Check out my latest blog post on microservices",
            original_text="Check out my latest blog post on microservices https://t.co/abc123",
            created_at=datetime(2024, 1, 8, 12, 0, tzinfo=timezone.utc),
            is_reply=False,
            like_count=15,
            retweet_count=3,
            reply_count=2,
            language="en",
        ),
    ]


@pytest.fixture
def sample_user_profile() -> UserProfile:
    """Return a realistic user profile for testing."""
    return UserProfile(
        username="techdev42",
        display_name="Tech Developer",
        bio="Full-stack dev | Open source enthusiast | Building cool stuff with Python & TypeScript | Opinions are my own",
        followers_count=12500,
        following_count=890,
        tweet_count=4200,
    )


@pytest.fixture
def sample_voice_profile() -> VoiceProfile:
    """Return a complete VoiceProfile with realistic values for all fields."""
    return VoiceProfile(
        username="techdev42",
        display_name="Tech Developer",
        bio="Full-stack dev | Open source enthusiast | Building cool stuff",
        schema_version="1.0.0",
        profile_built_at=datetime(2024, 2, 1, 12, 0, 0, tzinfo=timezone.utc),
        tweet_count_analyzed=500,
        date_range_start=datetime(2023, 6, 1, tzinfo=timezone.utc),
        date_range_end=datetime(2024, 1, 31, tzinfo=timezone.utc),
        structural_style=StructuralStyle(
            avg_tweet_length=142.5,
            tweet_length_distribution=TweetLengthDistribution(
                mean=142.5,
                median=135.0,
                std=55.3,
                min=4,
                max=280,
                p25=95.0,
                p75=195.0,
                histogram={"0-50": 35, "51-100": 85, "101-150": 120, "151-200": 150, "201-280": 110},
            ),
            avg_sentence_length=12.3,
            vocabulary_richness={
                "ttr": 0.42,
                "root_ttr": 8.5,
                "cttr": 6.0,
                "mtld": 72.5,
                "yules_k": 120.0,
                "hapax_ratio": 0.45,
            },
            top_vocabulary=[
                ("code", 85),
                ("build", 62),
                ("feature", 48),
                ("data", 45),
                ("work", 42),
                ("team", 38),
                ("ship", 35),
                ("test", 33),
                ("deploy", 30),
                ("api", 28),
            ],
            punctuation_patterns=PunctuationPatterns(
                period=45.0,
                comma=38.0,
                exclamation=22.0,
                question=15.0,
                ellipsis=3.5,
                em_dash=2.0,
                parentheses=5.0,
                quotation=3.0,
                semicolon=1.0,
                colon=8.0,
            ),
            capitalization_patterns=CapitalizationPatterns(
                all_caps_ratio=0.03,
                initial_caps_ratio=0.85,
                lowercase_start_ratio=0.12,
                mid_caps_ratio=0.02,
            ),
            fragment_ratio=0.25,
            question_ratio=0.18,
            exclamation_ratio=0.15,
            pos_distribution={
                "noun_ratio": 0.28,
                "verb_ratio": 0.22,
                "adj_ratio": 0.10,
                "adv_ratio": 0.06,
                "pronoun_ratio": 0.12,
                "function_word_ratio": 0.35,
            },
            readability_scores=ReadabilityScores(
                flesch_reading_ease=72.5,
                coleman_liau_index=8.2,
                automated_readability_index=7.8,
                gunning_fog=9.5,
            ),
        ),
        emoji_profile=EmojiProfile(
            usage_rate=0.85,
            emoji_tweet_ratio=0.45,
            top_emojis=[
                ("\U0001f680", 45),
                ("\U0001f525", 32),
                ("\U0001f4af", 28),
                ("\U0001f389", 20),
                ("\U0001f64f", 15),
            ],
            positional_tendency={"leading": 0.15, "inline": 0.25, "trailing": 0.60},
            emoji_diversity=0.35,
            emoji_sentiment=0.65,
        ),
        hashtag_profile=HashtagProfile(
            usage_rate=0.45,
            top_hashtags=[
                ("buildinpublic", 35),
                ("python", 28),
                ("webdev", 22),
                ("opensource", 18),
                ("coding", 15),
            ],
            placement_style="trailing",
            casing_style="CamelCase",
        ),
        topic_profile=TopicProfile(
            topics_ranked=[
                TopicEntry(
                    name="Software Development",
                    importance=0.92,
                    keywords=["code", "build", "ship", "deploy", "feature"],
                ),
                TopicEntry(
                    name="Open Source",
                    importance=0.75,
                    keywords=["opensource", "github", "contribute", "community", "pr"],
                ),
                TopicEntry(
                    name="Career Growth",
                    importance=0.60,
                    keywords=["learn", "grow", "career", "mentor", "skills"],
                ),
            ],
            opinion_map=[
                OpinionEntry(
                    topic="Software Development",
                    sentiment_mean=0.72,
                    sentiment_std=0.15,
                    label="enthusiastic",
                ),
                OpinionEntry(
                    topic="Open Source",
                    sentiment_mean=0.65,
                    sentiment_std=0.20,
                    label="generally_positive",
                ),
            ],
            semantic_clusters=[
                SemanticCluster(
                    cluster_id=0,
                    label="Coding Projects",
                    size=120,
                    keywords=["project", "code", "build"],
                    representative_tweets=[
                        "Just shipped a new feature!",
                        "The codebase is so much cleaner now",
                    ],
                ),
            ],
        ),
        personality_profile=PersonalityProfile(
            formality_score=0.35,
            humor_style="dry",
            tone="casual",
            big_five=BigFiveScores(
                openness=0.78,
                conscientiousness=0.72,
                extraversion=0.65,
                agreeableness=0.60,
                neuroticism=0.30,
            ),
            rhetorical_devices=["hyperbole", "rhetorical_question"],
            catchphrases=["ship it!", "let's gooo", "not gonna lie"],
            assertiveness=0.68,
        ),
        reply_style=ReplyStyle(
            avg_reply_length=95.2,
            opening_patterns={
                "greeting": 0.05,
                "direct": 0.45,
                "quote": 0.10,
                "emoji_lead": 0.15,
                "agreement": 0.20,
                "disagreement": 0.05,
            },
            tone_vs_originals="more_casual",
            engagement_type="supportive",
            length_ratio=0.72,
            sentiment_diff=0.05,
        ),
        example_tweets=ExampleTweets(
            originals=[
                "Just shipped a new feature! Really proud of the team",
                "Hot take: tabs are better than spaces",
                "What's everyone building this weekend?",
            ],
            replies=[
                ("How do you handle deployment?", "We use GitHub Actions with auto-deploy to staging first"),
                ("Any tips for new devs?", "Read more code than you write. Seriously."),
            ],
        ),
        raw_statistics={"total_words": 15000, "unique_words": 3200},
    )


@pytest.fixture
def tmp_data_dir(tmp_path) -> Path:
    """Temporary data directory for storage tests."""
    data_dir = tmp_path / ".postlikeme"
    data_dir.mkdir(parents=True, exist_ok=True)
    return data_dir


@pytest.fixture
def app_config(tmp_data_dir) -> AppConfig:
    """AppConfig pointing to temporary directory."""
    return AppConfig(
        data_dir=tmp_data_dir,
        default_llm_provider="anthropic",
        default_llm_model="claude-sonnet-4-20250514",
        default_collector="archive",
        default_tweet_count=500,
        default_temperature=0.85,
    )
